mode: paper

tickers: [EURUSD, GBPUSD, USDJPY, USDCAD, AUDUSD, USDCHF]

user: blablabla
password: 1234

model_name: 'random_forest'
model: 'sklearn.ensemble.RandomForestClassifier'
model_params:
  'max_depth': 25
  'min_samples_leaf': 1
  'min_samples_split': 2
  'n_estimators': 120
  'random_state': 42

threshold_up: 0.80

threshold_down: 0.20

risk_percentage: 1

models: 'random_forest'

train_window: 480

train_period: 1 # frecuencia con la que se entrena

stop_loss_in_pips: 15

take_profits_in_pips: 30

periods_forward_target: 10

use_days_in_position: False

trading_strategy: backbone.strategies.macd_strategy

risk_percentage: 1
